Repository googleapis/java-apigee-connect, pull requests merged in 2021-09, with the labels that each got.

#68 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: apigeeconnect

#72 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: apigeeconnect

#78 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: apigeeconnect
